  services:

    postgre-db: 
      image: postgres:16.6
      restart: always
      ports: 
        ["6400:5432"]
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      container_name: postgre-db
      volumes:
        - ./postgres:/var/lib/postgresql/data

    redis:
      container_name: redis
      image: redis:8
      restart: always
      ports:
        - 6380:6379
      volumes:
        - ./redis:/data