  services:
    mongo_db:
      image: mongo:8
      restart: always
      ports:
        - 27018:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGO_DB}
      volumes:
        - ./mongo:/data/db

    redis:
      image: redis:8
      restart: always
      ports:
        - 6379:6379
      volumes:
        - ./redis:/data
      
    nest-template:
      depends_on:
        - redis
      ports:
        - 3000:3000
      build: 
        context: .
        dockerfile: Dockerfile.dev
      volumes:  
        - ./src:/usr/src/app/src
      command: npm run start:dev
      environment:
        AMBIENT: ${AMBIENT}
        CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
        CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
        CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}      
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
        CORS: ${CORS}
        JWT_SECRET: ${JWT_SECRET}
        JWT_SOURCE: ${JWT_SOURCE}
        MONGO_DB: ${MONGO_DB}
        MONGO_PASSWORD: ${MONGO_PASSWORD}
        MONGO_URL: ${MONGO_URL}
        MONGO_USER: ${MONGO_USER}
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
        REDIS_PORT: ${REDIS_PORT}
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PASS: ${SMTP_PASS}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USER: ${SMTP_USER}