export const authDescriptions = {
  created: 'User created successfully',
  loginSuccess: 'Login successful',
  invalidCredentials: 'Invalid credentials or inactive user',
  invalidData: 'Invalid input data',
  unauthorized: 'Unauthorized',
  forbidden: 'Forbidden',
  notFound: 'User not found',
  conflict: 'User already exists',
  confirmed: 'Account confirmed',
  tokenNotFound: 'Token not found, request a new one',
  tokenSent: 'Token sent to your email',
  resetTokenSent: 'The token to reset your account was sent to your email',
  passwordChanged: 'Password changed successfully',
};
